---
# config

common:
  cfg_file : dqn.sumocfg
  port : 8088
  server_ip : 127.0.0.1 #add your ip address here
  total_episodes : 1000
  log_level : info
  plot_results : False

sumo:
  start : true 
  quit_on_end : true 
  num_clients : 0 # for one agent num_clients = 0 else the num_clients = number of desired clients
  use_gui : false
  # badpoints: ['E2','E4','E7','E9']
  start_edges : [['E0'], ['E1'], ['E3'],['E11'],['E8']] #list of valid start edges len of start_edges should be equall to num_clients
  